movieproject1/movieapp/urls.py
from django.contrib import admin
from django.urls import path
from movieapp import views
app_name='movieapp'

urlpatterns = [
    path('',views.Movielistview.as_view(),name='index'),
    # path('addmovie',views.addmovie,name='addmovie'),
    path('add/',views.createview.as_view(),name="add_movie"),
    # path('viewmovie',views.viewmovie,name='viewmovie'),
    path('Moviedetail/<int:pk>/', views.Moviedetailview.as_view(), name='moviedetail'),
    path('update/<int:pk>/', views.updateview.as_view(), name='update'),
    path('delete/<int:pk>/', views.deleteview.as_view(), name='delete'),

]

movieproject1/movieproject1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject1/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.CharField(max_length=250)
    years=models.IntegerField()
    img=models.ImageField(upload_to='img',null=True,blank=True)

    def __str__(self):
        return self.name

movieproject1/movieapp/views.py
from django.shortcuts import render
from movieapp.models import movie
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
# Create your views here.

# def index(request):
#     movie=Movie.objects.all()
#     context={'movie_list':movie}
#     return render(request,"base.html",context)
class Movielistview(ListView):
    model=movie
    template_name="base.html"
    context_object_name="movie_list"

class Moviedetailview(DetailView):
    model=movie
    template_name="detail.html"
    context_objects_name="movie"

class createview(CreateView):
        model = movie
        template_name = "addmovie.html"
        fields=['name','desc','years','img']
        success_url=reverse_lazy('movieapp:index')


class updateview(UpdateView):
    model = movie
    template_name = "addmovie.html"
    fields = ['name', 'desc', 'years', 'img']
    success_url = reverse_lazy('movieapp:index')

class deleteview(DeleteView):
        model = movie
        template_name = "delete.html"
        success_url = reverse_lazy('movieapp:index')


# def addmovie(request):
#     if(request.method=="POST"):
#         n=request.POST['n']
#         d=request.POST['d']
#         y=request.POST['y']
#         i=request.FILES['i']
#         m=movie.objects.create(name=n, desc=d, years=y, img=i)
#         m.save()
#         return home(request)
#     return render(request,'addmovie.html')


# def home(request):
#     m=movie.objects.all()
#     return render(request,'home.html',{'m':m})
# def viewmovie(request):
#     m=movie.objects.get()
#     return render(request,'viewmovie.html',{'m':m})

movieproject1/templates/addmovie.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--<h1>Add Books</h1>-->
<!--<form method="POST" enctype="multipart/form-data">-->
<!--    {% csrf_token %}-->
<!--<div class="mb-3">-->
<!--  <label  class="form-label">Name</label>-->
<!--  <input type="text" class="form-control" name="n"  placeholder="Enter Name">-->
<!--</div>-->
<!--    <div class="mb-3">-->
<!--  <label  class="form-label">Desc</label>-->
<!--  <input type="text" class="form-control"name="d"  placeholder="Enter Desc">-->
<!--</div>-->
<!--    <div class="mb-3">-->
<!--  <label  class="form-label">Years</label>-->
<!--  <input type="number" class="form-control"name="y"  placeholder="Enter Years">-->
<!--</div>-->

<!--    <div class="mb-3">-->
<!--  <label  class="form-label">Image</label>-->
<!--  <input type="file" class="form-control"name="i"  placeholder="Enter Image">-->
<!--</div>-->


<!--<div class="mb-3">-->
<!--  <input type="submit" class="btn btn-primary">-->
<!--</div>-->
<!--    </form>-->
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit">
</form>
{% endblock %}

movieproject1/templates/base.html
<!DOCTYPE html>
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>
<body>
<div id="new">
<nav class="navbar navbar-expand-lg  bg-body-tertiary">
  <div class="container-fluid">
        <div class="container-fluid">
          <a id="new1" class="nav-link active" aria-current="page" href="{%url 'movieapp:index' %}">online stores</a>

            <a class="btn btn-success" style="position:absolute; right:60px;" href="{%url 'movieapp:add_movie' %}">Add movie</a>
        </div>






    </div>
</nav>
{% block content %}
{% endblock %}
</div>
</body>
</html>

movieproject1/templates/delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    Are you want to delete this movie?
    <input type="submit">
</form>





{% endblock %}

movieproject1/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="row">
  <div class="col-sm-4">
    <img src="{{movie.img.url}}" class="card-img-top" alt="..." height="250px">
    </div>
    <div class="col-sm-6 mt-5">
     <a href="{% url 'movieapp:update' movie.id  %}" class="btn btn-primary">Update</a>
      <a href="{% url 'movieapp:delete' movie.id  %}" class="btn btn-primary">Delete</a>
    </div>
  </div>





{% endblock %}

movieproject1/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="card" style="width: 18rem;">
  <img src="{{i.img.url}}" class="card-img-top" alt="..." height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:viewmovie'%}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>



{% endblock %}

movieproject1/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-sm-3 col-md-3">
            <div class="card" style="width: 18rem;">
                 <img src="{{i.img.url}}" height="250px",width="100%" class="card-img-top" alt="...">
                 <div class="card-body">
                      <h5 class="card-title">{{i.name}}</h5>
                     <h5 class="card-title">{{i.desc}}</h5>

                      <a href="{% url 'movieapp:moviedetail' i.id %}" class="btn btn-primary" style="text:center">details</a>
                 </div>
            </div>
        </div>
         {% endfor %}
    </div>
</div>
{% endblock %}

movieproject1/templates/viewmovie.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="card" style="width: 18rem;">
  <img src="{{i.img.url}}" class="card-img-top" alt="..." height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
  </div>
</div>
{% endblock %}